### ISSUE TITLE
Enemy feedback

### ISSUE THREAD

**Issue by EthanHair** [astro-panda/ldjam-52#172]
There is better feedback when an enemy is hit
- Perhaps the enemy flashes white for a moment when hit and the sprite shifts away from the impact slightly

**Comment by Psypher9** [comment]
Enemy crumbles to dust and blows away?

**Comment by EthanHair** [comment]
Lol I was thinking this would be for every hit and there could be another story for adding a death animation (e.g. falling down, face covered in poo, then fades away)

**Comment by Psypher9** [comment]
Yeah I misread this at first

**Comment by Psypher9** [comment]
I should make the goblin hit sounds
